#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""Relay a locally-attached Keybow 2040 to a macropad daemon on another machine.

Run this on the machine the pad is physically plugged into. It reads the pad's
USB serial port and forwards the line-delimited JSON protocol, in both
directions, to the daemon's bridge listener.

This is the piece that makes the pad work over RDP: the daemon has to run where
the Copilot app's state lives, but the pad enumerates on whichever machine you
are sitting at.

It deliberately depends on nothing but ``pyserial``, so it can be copied to a
machine that has none of the rest of this project on it::

    pip install pyserial
    python pad_bridge.py --host <daemon-host> --token <token>

The token is generated by the daemon on first run and stored in
``~/.copilot/macropad.token`` on the daemon's machine.
"""

from __future__ import annotations

import argparse
import json
import logging
import socket
import sys
import time

try:
    import serial
    from serial.tools import list_ports
except ImportError:  # pragma: no cover - dependency guidance
    print("pyserial is required:  pip install pyserial", file=sys.stderr)
    raise SystemExit(1)

log = logging.getLogger("pad_bridge")

CIRCUITPYTHON_VIDS = (0x2E8A, 0x239A, 0x16D0)
RECONNECT_DELAY = 2.0
PROBE_TIMEOUT = 3.5
DEFAULT_PORT = 7831


def candidate_ports() -> list[str]:
    matches, others = [], []
    for info in list_ports.comports():
        (matches if info.vid in CIRCUITPYTHON_VIDS else others).append(info)

    def rank(info):
        hwid = (info.hwid or "").upper()
        hint = 1 if ("MI_02" in hwid or "MI_04" in hwid or "X.2" in hwid) else 0
        return (-hint, info.device)

    if matches:
        matches.sort(key=rank)
        return [i.device for i in matches]
    return [i.device for i in others]


def probe(port: str, baud: int) -> bool:
    """True if this port speaks the pad protocol."""
    try:
        with serial.Serial(port, baud, timeout=0.2) as handle:
            try:
                handle.write(b'{"t":"hb"}\n')
            except serial.SerialException:
                pass
            deadline = time.monotonic() + PROBE_TIMEOUT
            while time.monotonic() < deadline:
                line = handle.readline()
                if not line:
                    continue
                try:
                    message = json.loads(line.decode("utf-8").strip())
                except (ValueError, UnicodeDecodeError):
                    continue
                if isinstance(message, dict) and "t" in message:
                    return True
    except (serial.SerialException, OSError):
        return False
    return False


def find_pad(explicit: str | None, baud: int) -> str | None:
    if explicit:
        return explicit if probe(explicit, baud) else None
    for port in candidate_ports():
        log.debug("probing %s", port)
        if probe(port, baud):
            return port
    return None


def relay(pad: serial.Serial, sock: socket.socket) -> None:
    """Pump bytes both ways until either side goes away."""
    sock.settimeout(0.1)
    net_buffer = b""

    while True:
        # Pad -> daemon
        try:
            waiting = pad.in_waiting
            if waiting:
                chunk = pad.read(waiting)
                if chunk:
                    sock.sendall(chunk)
        except (serial.SerialException, OSError):
            log.warning("pad went away")
            return

        # Daemon -> pad
        try:
            data = sock.recv(512)
            if not data:
                log.warning("daemon closed the connection")
                return
            net_buffer += data
            while b"\n" in net_buffer:
                line, _, net_buffer = net_buffer.partition(b"\n")
                pad.write(line + b"\n")
        except socket.timeout:
            pass
        except (OSError, serial.SerialException):
            log.warning("link lost")
            return

        time.sleep(0.005)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--host", required=True, help="daemon host (the machine running Copilot)")
    parser.add_argument("--port", type=int, default=DEFAULT_PORT)
    parser.add_argument("--token", help="shared bridge token")
    parser.add_argument("--token-file", help="file containing the shared bridge token")
    parser.add_argument("--serial", help="pad serial port; auto-detected when omitted")
    parser.add_argument("--baud", type=int, default=115200)
    parser.add_argument("--verbose", "-v", action="store_true")
    args = parser.parse_args(argv)

    logging.basicConfig(
        level=logging.DEBUG if args.verbose else logging.INFO,
        format="%(asctime)s %(levelname)-7s %(message)s",
        datefmt="%H:%M:%S",
    )

    token = args.token
    if not token and args.token_file:
        with open(args.token_file, encoding="utf-8") as handle:
            token = handle.read().strip()
    if not token:
        parser.error("one of --token or --token-file is required")

    log.info("bridging pad -> %s:%d", args.host, args.port)

    while True:
        port = find_pad(args.serial, args.baud)
        if port is None:
            log.info("keybow not found; retrying")
            time.sleep(RECONNECT_DELAY)
            continue

        try:
            pad = serial.Serial(port, args.baud, timeout=0.2)
        except (serial.SerialException, OSError) as exc:
            log.warning("could not open %s: %s", port, exc)
            time.sleep(RECONNECT_DELAY)
            continue

        log.info("pad on %s", port)
        try:
            with socket.create_connection((args.host, args.port), timeout=10) as sock:
                sock.sendall(json.dumps({"t": "auth", "token": token}).encode() + b"\n")
                log.info("connected to daemon")
                relay(pad, sock)
        except OSError as exc:
            log.warning("daemon unreachable: %s", exc)
        finally:
            pad.close()

        time.sleep(RECONNECT_DELAY)


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except KeyboardInterrupt:
        raise SystemExit(0)
