#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""Relay a locally-attached Keybow 2040 to a macropad daemon on another machine.

Run this on the machine the pad is physically plugged into. It reads the pad's
USB serial port and forwards the line-delimited JSON protocol, in both
directions, to the daemon's bridge listener.

This is the piece that makes the pad work over RDP: the daemon has to run where
the Copilot app's state lives, but the pad enumerates on whichever machine you
are sitting at.

It deliberately depends on nothing but ``pyserial``, so it can be copied to a
machine that has none of the rest of this project on it::

    pip install pyserial
    python pad_bridge.py --host <daemon-host> --token-file macropad.token

If the remote machine cannot accept inbound connections, reverse the direction::

    python pad_bridge.py --listen --token-file macropad.token

The token is generated by the daemon on first run and stored in
``~/.copilot/macropad.token`` on the daemon's machine.
"""

from __future__ import annotations

import argparse
import json
import logging
import secrets
import socket
import sys
import time

try:
    import serial
    from serial.tools import list_ports
except ImportError:  # pragma: no cover - dependency guidance
    print("pyserial is required:  pip install pyserial", file=sys.stderr)
    raise SystemExit(1)

log = logging.getLogger("pad_bridge")

CIRCUITPYTHON_VIDS = (0x2E8A, 0x239A, 0x16D0)
RECONNECT_DELAY = 2.0
PROBE_TIMEOUT = 3.5
DEFAULT_PORT = 7831
AUTH_TIMEOUT = 5.0
CONNECTION_TEST_TIMEOUT = 2.0


def candidate_ports() -> list[str]:
    matches, others = [], []
    for info in list_ports.comports():
        (matches if info.vid in CIRCUITPYTHON_VIDS else others).append(info)

    def rank(info):
        hwid = (info.hwid or "").upper()
        hint = 1 if ("MI_02" in hwid or "MI_04" in hwid or "X.2" in hwid) else 0
        return (-hint, info.device)

    if matches:
        matches.sort(key=rank)
        return [i.device for i in matches]
    return [i.device for i in others]


def probe(port: str, baud: int) -> bool:
    """True if this port speaks the pad protocol."""
    try:
        with serial.Serial(port, baud, timeout=0.2) as handle:
            try:
                handle.dtr = True
            except (OSError, serial.SerialException):
                pass

            # Listen only. CircuitPython exposes a console and a data port; the
            # console echoes whatever is written to it, so writing a JSON probe
            # and accepting the echo falsely identifies the console as the pad.
            # The firmware emits hello/heartbeat frames on the data port without
            # being prompted, which is both safer and sufficient.
            buffer = b""
            deadline = time.monotonic() + PROBE_TIMEOUT
            while time.monotonic() < deadline:
                try:
                    waiting = handle.in_waiting
                except (OSError, serial.SerialException):
                    return False
                if not waiting:
                    time.sleep(0.05)
                    continue
                buffer += handle.read(waiting)
                while b"\n" in buffer:
                    raw, _, buffer = buffer.partition(b"\n")
                    try:
                        message = json.loads(raw.decode("utf-8").strip())
                    except (ValueError, UnicodeDecodeError):
                        continue
                    if isinstance(message, dict) and message.get("t") in ("hb", "hello"):
                        return True
    except (serial.SerialException, OSError):
        return False
    return False


def find_pad(explicit: str | None, baud: int) -> str | None:
    if explicit:
        return explicit if probe(explicit, baud) else None
    for port in candidate_ports():
        log.debug("probing %s", port)
        if probe(port, baud):
            return port
    return None


def relay(pad: serial.Serial, sock: socket.socket, initial_network_data: bytes = b"") -> None:
    """Pump bytes both ways until either side goes away."""
    sock.settimeout(0.1)
    net_buffer = initial_network_data

    while True:
        # Pad -> daemon
        try:
            waiting = pad.in_waiting
            if waiting:
                chunk = pad.read(waiting)
                if chunk:
                    sock.sendall(chunk)
        except (serial.SerialException, OSError):
            log.warning("pad went away")
            return

        # Daemon -> pad. Authentication and the first LED update can arrive in
        # one packet when the daemon dials us, so process bytes preserved by
        # accept_daemon before waiting for another recv.
        while b"\n" in net_buffer:
            line, _, net_buffer = net_buffer.partition(b"\n")
            pad.write(line + b"\n")

        try:
            data = sock.recv(512)
            if not data:
                log.warning("daemon closed the connection")
                return
            net_buffer += data
        except socket.timeout:
            pass
        except (OSError, serial.SerialException):
            log.warning("link lost")
            return

        time.sleep(0.005)


def connect_daemon(host: str, port: int, token: str) -> socket.socket:
    """Dial the daemon and authenticate as the bridge."""
    sock = socket.create_connection((host, port), timeout=10)
    sock.sendall(json.dumps({"t": "auth", "token": token}).encode() + b"\n")
    return sock


def accept_daemon(listener: socket.socket, token: str) -> tuple[socket.socket, bytes]:
    """Accept a daemon connection and return bytes received after its auth frame."""
    while True:
        sock, address = listener.accept()
        sock.settimeout(AUTH_TIMEOUT)
        buffer = b""
        try:
            while b"\n" not in buffer and len(buffer) < 4096:
                chunk = sock.recv(256)
                if not chunk:
                    break
                buffer += chunk
            line, separator, remainder = buffer.partition(b"\n")
            message = json.loads(line.decode("utf-8"))
            presented = str(message.get("token", ""))
        except (OSError, ValueError, UnicodeDecodeError):
            log.warning("connection from %s failed to authenticate", address[0])
            sock.close()
            continue

        if not separator or not secrets.compare_digest(presented, token):
            log.warning("connection from %s presented a bad token", address[0])
            sock.close()
            continue

        sock.settimeout(None)
        log.info("daemon connected from %s", address[0])
        return sock, remainder


def test_daemon_connection(host: str, port: int, token: str) -> str:
    """Return ``ok``, ``rejected``, or ``unreachable`` without opening the pad."""
    try:
        sock = connect_daemon(host, port, token)
    except OSError:
        return "unreachable"

    with sock:
        try:
            sock.sendall(b'{"t":"hb"}\n')
        except OSError:
            return "rejected"
        sock.settimeout(CONNECTION_TEST_TIMEOUT)
        try:
            data = sock.recv(256)
            return "ok" if data else "rejected"
        except socket.timeout:
            # The authenticated daemon may have no state change to send.
            # A still-open socket after the same two-second read used by
            # the PowerShell bridge is an accepted, idle connection.
            return "ok"
        except OSError:
            return "rejected"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--host", help="daemon host (the machine running Copilot)")
    parser.add_argument("--port", type=int, default=DEFAULT_PORT)
    parser.add_argument("--token", help="shared bridge token")
    parser.add_argument("--token-file", help="file containing the shared bridge token")
    parser.add_argument("--serial", help="pad serial port; auto-detected when omitted")
    parser.add_argument("--baud", type=int, default=115200)
    parser.add_argument(
        "--listen",
        action="store_true",
        help="accept an outbound connection from the daemon instead of dialling it",
    )
    parser.add_argument(
        "--listen-host",
        default="0.0.0.0",
        help="interface to bind with --listen (default: all interfaces)",
    )
    parser.add_argument(
        "--test-connection",
        action="store_true",
        help="verify daemon reachability and authentication, then exit",
    )
    parser.add_argument("--verbose", "-v", action="store_true")
    args = parser.parse_args(argv)

    logging.basicConfig(
        level=logging.DEBUG if args.verbose else logging.INFO,
        format="%(asctime)s %(levelname)-7s %(message)s",
        datefmt="%H:%M:%S",
    )

    token = args.token
    if not token and args.token_file:
        with open(args.token_file, encoding="utf-8") as handle:
            token = handle.read().strip()
    if not token:
        parser.error("one of --token or --token-file is required")

    if args.listen and args.test_connection:
        parser.error("--test-connection cannot be used with --listen")
    if not args.listen and not args.host:
        parser.error("--host is required unless --listen is used")

    if args.test_connection:
        outcome = test_daemon_connection(args.host, args.port, token)
        if outcome == "ok":
            print(f"OK: daemon accepted the bridge on {args.host}:{args.port}")
            return 0
        if outcome == "rejected":
            print("REJECTED: the daemon is reachable but the token was not accepted", file=sys.stderr)
            return 2
        print(f"UNREACHABLE: cannot connect to {args.host}:{args.port}", file=sys.stderr)
        return 1

    listener = None
    if args.listen:
        listener = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        listener.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
        listener.bind((args.listen_host, args.port))
        listener.listen(1)
        log.info("waiting for daemon on %s:%d", args.listen_host, args.port)
    else:
        log.info("bridging pad -> %s:%d", args.host, args.port)

    try:
        while True:
            port = find_pad(args.serial, args.baud)
            if port is None:
                log.info("keybow not found; retrying")
                time.sleep(RECONNECT_DELAY)
                continue

            try:
                pad = serial.Serial(port, args.baud, timeout=0.2)
                try:
                    pad.dtr = True
                except (OSError, serial.SerialException):
                    pass
            except (serial.SerialException, OSError) as exc:
                log.warning("could not open %s: %s", port, exc)
                time.sleep(RECONNECT_DELAY)
                continue

            log.info("pad on %s", port)
            try:
                if listener is not None:
                    sock, initial_data = accept_daemon(listener, token)
                else:
                    sock = connect_daemon(args.host, args.port, token)
                    initial_data = b""
                    log.info("connected to daemon")
                with sock:
                    relay(pad, sock, initial_data)
            except OSError as exc:
                log.warning("daemon link unavailable: %s", exc)
            finally:
                pad.close()

            time.sleep(RECONNECT_DELAY)
    finally:
        if listener is not None:
            listener.close()


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except KeyboardInterrupt:
        raise SystemExit(0)
